// 47 Prefectures of Japan
export const PREFECTURES = [
  { value: "hokkaido", label: "北海道", labelEn: "Hokkaido" },
  { value: "aomori", label: "青森県", labelEn: "Aomori" },
  { value: "iwate", label: "岩手県", labelEn: "Iwate" },
  { value: "miyagi", label: "宮城県", labelEn: "Miyagi" },
  { value: "akita", label: "秋田県", labelEn: "Akita" },
  { value: "yamagata", label: "山形県", labelEn: "Yamagata" },
  { value: "fukushima", label: "福島県", labelEn: "Fukushima" },
  { value: "ibaraki", label: "茨城県", labelEn: "Ibaraki" },
  { value: "tochigi", label: "栃木県", labelEn: "Tochigi" },
  { value: "gunma", label: "群馬県", labelEn: "Gunma" },
  { value: "saitama", label: "埼玉県", labelEn: "Saitama" },
  { value: "chiba", label: "千葉県", labelEn: "Chiba" },
  { value: "tokyo", label: "東京都", labelEn: "Tokyo" },
  { value: "kanagawa", label: "神奈川県", labelEn: "Kanagawa" },
  { value: "niigata", label: "新潟県", labelEn: "Niigata" },
  { value: "toyama", label: "富山県", labelEn: "Toyama" },
  { value: "ishikawa", label: "石川県", labelEn: "Ishikawa" },
  { value: "fukui", label: "福井県", labelEn: "Fukui" },
  { value: "yamanashi", label: "山梨県", labelEn: "Yamanashi" },
  { value: "nagano", label: "長野県", labelEn: "Nagano" },
  { value: "gifu", label: "岐阜県", labelEn: "Gifu" },
  { value: "shizuoka", label: "静岡県", labelEn: "Shizuoka" },
  { value: "aichi", label: "愛知県", labelEn: "Aichi" },
  { value: "mie", label: "三重県", labelEn: "Mie" },
  { value: "shiga", label: "滋賀県", labelEn: "Shiga" },
  { value: "kyoto", label: "京都府", labelEn: "Kyoto" },
  { value: "osaka", label: "大阪府", labelEn: "Osaka" },
  { value: "hyogo", label: "兵庫県", labelEn: "Hyogo" },
  { value: "nara", label: "奈良県", labelEn: "Nara" },
  { value: "wakayama", label: "和歌山県", labelEn: "Wakayama" },
  { value: "tottori", label: "鳥取県", labelEn: "Tottori" },
  { value: "shimane", label: "島根県", labelEn: "Shimane" },
  { value: "okayama", label: "岡山県", labelEn: "Okayama" },
  { value: "hiroshima", label: "広島県", labelEn: "Hiroshima" },
  { value: "yamaguchi", label: "山口県", labelEn: "Yamaguchi" },
  { value: "tokushima", label: "徳島県", labelEn: "Tokushima" },
  { value: "kagawa", label: "香川県", labelEn: "Kagawa" },
  { value: "ehime", label: "愛媛県", labelEn: "Ehime" },
  { value: "kochi", label: "高知県", labelEn: "Kochi" },
  { value: "fukuoka", label: "福岡県", labelEn: "Fukuoka" },
  { value: "saga", label: "佐賀県", labelEn: "Saga" },
  { value: "nagasaki", label: "長崎県", labelEn: "Nagasaki" },
  { value: "kumamoto", label: "熊本県", labelEn: "Kumamoto" },
  { value: "oita", label: "大分県", labelEn: "Oita" },
  { value: "miyazaki", label: "宮崎県", labelEn: "Miyazaki" },
  { value: "kagoshima", label: "鹿児島県", labelEn: "Kagoshima" },
  { value: "okinawa", label: "沖縄県", labelEn: "Okinawa" },
];

// Common countries for Japanese learners
export const COUNTRIES = [
  { value: "US", label: "United States", flag: "🇺🇸" },
  { value: "GB", label: "United Kingdom", flag: "🇬🇧" },
  { value: "CA", label: "Canada", flag: "🇨🇦" },
  { value: "AU", label: "Australia", flag: "🇦🇺" },
  { value: "NZ", label: "New Zealand", flag: "🇳🇿" },
  { value: "DE", label: "Germany", flag: "🇩🇪" },
  { value: "FR", label: "France", flag: "🇫🇷" },
  { value: "IT", label: "Italy", flag: "🇮🇹" },
  { value: "ES", label: "Spain", flag: "🇪🇸" },
  { value: "NL", label: "Netherlands", flag: "🇳🇱" },
  { value: "BE", label: "Belgium", flag: "🇧🇪" },
  { value: "SE", label: "Sweden", flag: "🇸🇪" },
  { value: "NO", label: "Norway", flag: "🇳🇴" },
  { value: "DK", label: "Denmark", flag: "🇩🇰" },
  { value: "FI", label: "Finland", flag: "🇫🇮" },
  { value: "CH", label: "Switzerland", flag: "🇨🇭" },
  { value: "AT", label: "Austria", flag: "🇦🇹" },
  { value: "PL", label: "Poland", flag: "🇵🇱" },
  { value: "CZ", label: "Czech Republic", flag: "🇨🇿" },
  { value: "HU", label: "Hungary", flag: "🇭🇺" },
  { value: "RU", label: "Russia", flag: "🇷🇺" },
  { value: "UA", label: "Ukraine", flag: "🇺🇦" },
  { value: "CN", label: "China", flag: "🇨🇳" },
  { value: "TW", label: "Taiwan", flag: "🇹🇼" },
  { value: "HK", label: "Hong Kong", flag: "🇭🇰" },
  { value: "KR", label: "South Korea", flag: "🇰🇷" },
  { value: "TH", label: "Thailand", flag: "🇹🇭" },
  { value: "VN", label: "Vietnam", flag: "🇻🇳" },
  { value: "PH", label: "Philippines", flag: "🇵🇭" },
  { value: "ID", label: "Indonesia", flag: "🇮🇩" },
  { value: "MY", label: "Malaysia", flag: "🇲🇾" },
  { value: "SG", label: "Singapore", flag: "🇸🇬" },
  { value: "IN", label: "India", flag: "🇮🇳" },
  { value: "PK", label: "Pakistan", flag: "🇵🇰" },
  { value: "BD", label: "Bangladesh", flag: "🇧🇩" },
  { value: "BR", label: "Brazil", flag: "🇧🇷" },
  { value: "MX", label: "Mexico", flag: "🇲🇽" },
  { value: "AR", label: "Argentina", flag: "🇦🇷" },
  { value: "CL", label: "Chile", flag: "🇨🇱" },
  { value: "CO", label: "Colombia", flag: "🇨🇴" },
  { value: "PE", label: "Peru", flag: "🇵🇪" },
  { value: "ZA", label: "South Africa", flag: "🇿🇦" },
  { value: "EG", label: "Egypt", flag: "🇪🇬" },
  { value: "NG", label: "Nigeria", flag: "🇳🇬" },
  { value: "KE", label: "Kenya", flag: "🇰🇪" },
  { value: "AE", label: "United Arab Emirates", flag: "🇦🇪" },
  { value: "SA", label: "Saudi Arabia", flag: "🇸🇦" },
  { value: "TR", label: "Turkey", flag: "🇹🇷" },
  { value: "IL", label: "Israel", flag: "🇮🇱" },
  { value: "OTHER", label: "Other", flag: "🌍" },
];

// Get prefecture label by value
export function getPrefectureLabel(value: string): string {
  const prefecture = PREFECTURES.find(p => p.value === value);
  return prefecture ? prefecture.label : value;
}

// Get country info by value
export function getCountryInfo(value: string): { label: string; flag: string } {
  const country = COUNTRIES.find(c => c.value === value);
  return country ? { label: country.label, flag: country.flag } : { label: value, flag: "🌍" };
}
